In [68]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split 
from sklearn import metrics
import numpy as np
import pandas as pd

In [69]:

# Read dataset
golf_data=pd.read_csv("golf.csv")

# show top 5 results
golf_data.head()

    OUTLOOK TEMPERATURE HUMIDITY  WINDY PLAY_GOLF
0     Rainy         Hot     High  False        No
1     Rainy         Hot     High   True        No
2  Overcast         Hot     High  False       Yes
3     Sunny        Mild     High  False       Yes
4     Sunny        Cool   Normal  False       Yes

In [70]:
# Map string vales for Outlook column to numbers
d = {'Sunny': 1, 'Overcast': 2, 'Rainy': 3}
golf_data.OUTLOOK = [d[item] for item in golf_data.OUTLOOK.astype(str)]

e = {'Hot': 1, 'Mild': 2, 'Cool': 3}
golf_data.TEMPERATURE = [e[item] for item in golf_data.TEMPERATURE.astype(str)]

f = {'High': 1, 'Normal': 0}
golf_data.HUMIDITY= [f[item] for item in golf_data.HUMIDITY.astype(str)]

g = {'False': 0, 'True': 1}
golf_data.WINDY = [g[item] for item in golf_data.WINDY.astype(str)] 

golf_data.head(10)

   OUTLOOK  TEMPERATURE  HUMIDITY  WINDY PLAY_GOLF
0        3            1         1      0        No
1        3            1         1      1        No
2        2            1         1      0       Yes
3        1            2         1      0       Yes
4        1            3         0      0       Yes
5        1            3         0      1        No
6        2            3         0      1       Yes
7        3            2         1      0        No
8        3            3         0      0       Yes
9        1            2         0      0       Yes

In [71]:
#split dataset in features and target variable
feature_cols = ['OUTLOOK','TEMPERATURE','HUMIDITY','WINDY']
X = golf_data[feature_cols] # Features
y =golf_data.PLAY_GOLF # Target variable

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.3, random_state=1)

print(X_train)

    OUTLOOK  TEMPERATURE  HUMIDITY  WINDY
4         1            3         0      0
1         3            1         1      1
12        2            1         0      0
0         3            1         1      0
13        1            2         1      1
9         1            2         0      0
8         3            3         0      0
11        2            2         1      1
5         1            3         0      1

In [72]:
# initialise Gaussian Naive Bayes
naive_b = GaussianNB()

# Train Decision Tree Classifer
naive_b = naive_b.fit(X_train,Y_train)

test_label_custom = np.array([2,1,0,0])

#Predict the response for test dataset
y_pred = naive_b.predict([test_label_custom])

print(y_pred)

['Yes']